pip3 install torch
pip3 install pandas
pip install gymnasium
pip install gym
pip install tensorboardX
pip install gymnasium-robotics
pip install tensorboard
pip install matplotlib
pip install seaborn
